apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: nginx-rs

spec:
  replicas: 4

  selector:
    matchLabels:
      app: nginx-app
      project: k8s

  template:
    metadata:
      labels:
        app: nginx-app
        env: dev
        tier: frontend
        project: k8s
    spec:
      containers:
        - name: nginx-container
          image: nginx:stable
          ports:
            - containerPort: 80
